/**
 * Static preset sketches shown in <preset-selector>.
 *
 * Each entry: `{ title, description, code, requires? }`. `code` is a string
 * (multi-line assembled with `Array.join('\n')` so leading tabs/whitespace
 * stay readable here). `requires` is informational metadata only —
 * consumers decide whether to apply it before evaluating.
 */
export const PRESETS = [
  {
    title: 'osc',
    description: 'basic oscillator — default synth output',
    code: 'osc(10, 0.2, 0.5).out()',
  },
  {
    title: 'noise',
    description: 'colored noise — noise() + .color()',
    code: 'noise(3, 0.1).color(0.5, 0.5, 0.5).out()',
  },
  {
    title: 'cam + blend',
    description: 'camera + screen blend — requires sources=2',
    code: 's0.initCam(); s1.initScreen(); src(s0).blend(src(s1)).out()',
    requires: { sources: 2 },
  },
  {
    title: 'custom GLSL',
    description: 'user-defined src — noixe() via setFunction()',
    code: 'noixe(5, 0.5).out()',
  },
  {
    title: 'typo (error)',
    description: 'intentional typo — verifies hydra-eval error reporting',
    code: 'osC(10, 0.2, 0.5).out()',
  },
  {
    title: 'reset',
    description: 'clear sources, hush, solid black — restores default state',
    code: 'for (let i = 0; i < s.length; i++) s[i].clear(); hush(); solid(0, 0, 0).out()',
  },
  {
    title: 'corrupted screensaver',
    description: 'by Ritchse (CC BY-NC-SA 4.0) — voronoi + diff chain',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=ritchse_1',
      '// licensed with CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/',
      '//corrupted screensaver',
      '//by Ritchse',
      '//instagram.com/ritchse',
      '',
      'voronoi(350,0.15)',
      '\t.modulateScale(osc(8).rotate(Math.sin(time)),.5)',
      '\t.thresh(.8)',
      '\t.modulateRotate(osc(7),.4)',
      '\t.thresh(.7)',
      '\t.diff(src(o0).scale(1.8))',
      '\t.modulateScale(osc(2).modulateRotate(o0,.74))',
      '\t.diff(src(o0).rotate([-.012,.01,-.002,0]).scrollY(0,[-1/199800,0].fast(0.7)))',
      '\t.brightness([-.02,-.17].smooth().fast(.5))',
      '\t.out()',
    ].join('\n'),
  },
  {
    title: 'glitch river',
    description: 'by Flor de Fuego — voronoi + kaleid feedback',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=flor_2',
      '//Glitch River',
      '//Flor de Fuego',
      '//https://flordefuego.github.io/',
      '',
      'voronoi(8,1)',
      '.mult(osc(10,0.1,()=>Math.sin(time)*3).saturate(3).kaleid(200))',
      '.modulate(o0,0.5)',
      '.add(o0,0.8)',
      '.scrollY(-0.01)',
      '.scale(0.99)',
      '.modulate(voronoi(8,1),0.008)',
      '.luma(0.3)',
      '.out()',
      '',
      '',
      'speed = 0.1',
      '',
      '',
    ].join('\n'),
  },
  {
    title: 'osc + kaleid',
    description: 'by Zach Krall (CC BY-NC-SA 4.0) — osc.diff + repeat modulate',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=example_11',
      '// licensed with CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/',
      '// by Zach Krall',
      '// http://zachkrall.online/',
      '',
      'osc(10, 0.9, 300)',
      '.color(0.9, 0.7, 0.8)',
      '.diff(',
      '  osc(45, 0.3, 100)',
      '  .color(0.9, 0.9, 0.9)',
      '  .rotate(0.18)',
      '  .pixelate(12)',
      '  .kaleid()',
      ')',
      '.scrollX(10)',
      '.colorama()',
      '.luma()',
      '.repeatX(4)',
      '.repeatY(4)',
      '.modulate(',
      '  osc(1, -0.9, 300)',
      ')',
      '.scale(2)',
      '.out()',
    ].join('\n'),
  },
  {
    title: 'osc + mouse rotate',
    description: 'by Olivia Jack — pixelated osc with mouse-driven modulateRotate',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=example_18',
      '// by Olivia Jack',
      '// https://ojack.github.io',
      '',
      'osc(6, 0, 0.8)',
      '  .color(1.14, 0.6,.80)',
      '  .rotate(0.92, 0.3)',
      '  .pixelate(20, 10)',
      '  .mult(osc(40, 0.03).thresh(0.4).rotate(0, -0.02))',
      '  .modulateRotate(osc(20, 0).thresh(0.3, 0.6), () => 0.1 + mouse.x * 0.002)',
      '  .out(o0)',
    ].join('\n'),
  },
  {
    title: 'osc + modulatePixelate',
    description: 'by Naoto Hieda (@naoto_hieda) — chained outputs with pixelate modulation',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=naoto_0',
      '// @naoto_hieda',
      '',
      'osc(20, 0.1, 0).color(0, 1, 2).rotate(1.57/2).out(o1)',
      'osc(30, 0.01, 0).color(2, 0.7, 1).modulate(o1, 0).add(o1,1).modulatePixelate(o1,1,10).out(o0)',
    ].join('\n'),
  },
  {
    title: 'egg of the phoenix',
    description: 'by Alexandre Rangel — stacked shape.diff chain with modulateScale',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=alexandre_2',
      '// "egg of the phoenix"',
      '// Alexandre Rangel',
      '// www.alexandrerangel.art.br/hydra.html',
      '',
      'speed=1.2',
      'shape(99,.15,.5).color(0,1,2)',
      '',
      '.diff( shape(240,.5,0).scrollX(.05).rotate( ()=>time/10 ).color(1,0,.75) )',
      '.diff( shape(99,.4,.002).scrollX(.10).rotate( ()=>time/20 ).color(1,0,.75) )',
      '.diff( shape(99,.3,.002).scrollX(.15).rotate( ()=>time/30 ).color(1,0,.75) )',
      '.diff( shape(99,.2,.002).scrollX(.20).rotate( ()=>time/40 ).color(1,0,.75) )',
      '.diff( shape(99,.1,.002).scrollX(.25).rotate( ()=>time/50 ).color(1,0,.75) )',
      '',
      '.modulateScale(',
      '  shape(240,.5,0).scrollX(.05).rotate( ()=>time/10 )',
      '  , ()=>(Math.sin(time/3)*.2)+.2 )',
      '',
      '.scale(1.6,.6,1)',
      '.out()',
    ].join('\n'),
  },
  {
    title: 'really love',
    description: 'by Abhinay Khoparzi — osc.pixelate.kaleid + self-diff feedback',
    code: [
      '// from https://hydra.ojack.xyz/?sketch_id=khoparzi_2',
      '// Really Love',
      '// by Abhinay Khoparzi',
      '// http://khoparzi.com',
      '',
      'osc(100,-0.01245,1).pixelate(50).kaleid(()=>(Math.sin(time/8)*9+3)).rotate(0,0.125)',
      '.modulateRotate(shape(3).scale(()=>(Math.cos(time)*2)).rotate(0,-0.25)).diff(src(o0).brightness(0.3))',
      '  .out()',
    ].join('\n'),
  },
  {
    title: 'turb / warp / cwarp (4 outputs)',
    description: 'CC BY-NC-SA 4.0 — extra-shaders-for-hydra (metagrowing) on all outputs',
    code: [
      '// from https://hydra.ojack.xyz/?code=JTJGJTJGJTIwbGljZW5zZWQlMjB3aXRoJTIwQ0MlMjBCWS1OQy1TQSUyMDQuMCUyMGh0dHBzJTNBJTJGJTJGY3JlYXRpdmVjb21tb25zLm9yZyUyRmxpY2Vuc2VzJTJGYnktbmMtc2ElMkY0LjAlMkYlMEFhd2FpdCUyMGxvYWRTY3JpcHQoJTIyaHR0cHMlM0ElMkYlMkZtZXRhZ3Jvd2luZy5vcmclMkZleHRyYS1zaGFkZXJzLWZvci1oeWRyYSUyRmxpYi1ub2lzZS5qcyUyMiklMEElMEF0dXJiKDMlMkMlMjAwJTJDJTIwJTIwKCklMjAlM0QlM0UlMjA2JTIwKiUyMCgoMC41JTIwKiUyMHRpbWUpJTIwJTI1JTIwMS4wKSkub3V0KG8wKSUzQiUwQXV0dXJiKDMlMkMlMjAwJTJDJTIwKCklMjAlM0QlM0UlMjA2JTIwKiUyMCgoMC41JTIwKiUyMHRpbWUpJTIwJTI1JTIwMS4wKSkub3V0KG8xKSUzQiUwQXdhcnAoMyUyQyUyMDAlMkMlMjAlMjAoKSUyMCUzRCUzRSUyMDYlMjAqJTIwKCgwLjUlMjAqJTIwdGltZSklMjAlMjUlMjAxLjApJTJDJTIwKCklMjAlM0QlM0UlMjA2JTIwKiUyMCgoMC41JTIwKiUyMHRpbWUpJTIwJTI1JTIwMS4wKSkub3V0KG8yKSUzQiUwQWN3YXJwKDMlMkMlMjAwJTJDJTIwKCklMjAlM0QlM0UlMjA2JTIwKiUyMCgoMC41JTIwKiUyMHRpbWUpJTIwJTI1JTIwMS4wKSUyQyUyMCgpJTIwJTNEJTNFJTIwNiUyMColMjAoKDAuNSUyMColMjB0aW1lKSUyMCUyNSUyMDEuMCkpLm91dChvMyklM0IlMEFyZW5kZXIoKSUwQQ%3D%3D',
      '// licensed with CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/',
      'await loadScript("https://metagrowing.org/extra-shaders-for-hydra/lib-noise.js")',
      '',
      'turb(3, 0,  () => 6 * ((0.5 * time) % 1.0)).out(o0);',
      'uturb(3, 0, () => 6 * ((0.5 * time) % 1.0)).out(o1);',
      'warp(3, 0,  () => 6 * ((0.5 * time) % 1.0), () => 6 * ((0.5 * time) % 1.0))',
      '.out(o2);',
      'cwarp(3, 0, () => 6 * ((0.5 * time) % 1.0), () => 6 * ((0.5 * time) % 1.0)).out(o3);',
      'render()',
    ].join('\n'),
  },
  {
    title: 'osc + arithmetics',
    description: 'by geikha — hyper-hydra extension: .mod / .step / .unipolar / .div',
    code: [
      '// from https://hydra.ojack.xyz/?code=JTBBYXdhaXQlMjBsb2FkU2NyaXB0KCUyMmh0dHBzJTNBJTJGJTJGY2RuLmpzZGVsaXZyLm5ldCUyRmdoJTJGZ2Vpa2hhJTJGaHlwZXItaHlkcmElNDBsYXRlc3QlMkZoeWRyYS1hcml0aG1ldGljcy5qcyUyMiklMEElMEFvc2MoMTAlMkMuMSUyQzIpJTBBJTA5Lm1vZChncmFkaWVudCgpLmFzaW4oKS5jb3MoKSklMEElMDkuc3RlcChub2lzZSgyKS51bmlwb2xhcigpLmRpdihvMCkpJTBBJTA5LmJsZW5kKG8wJTJDLjIpJTBBJTA5Lm91dCgpJTBB',
      '',
      'await loadScript("https://cdn.jsdelivr.net/gh/geikha/hyper-hydra@latest/hydra-arithmetics.js")',
      '',
      'osc(10,.1,2)',
      '\t.mod(gradient().asin().cos())',
      '\t.step(noise(2).unipolar().div(o0))',
      '\t.blend(o0,.2)',
      '\t.out()',
    ].join('\n'),
  },
  {
    title: 'osc + blend modes',
    description: 'by geikha — hyper-hydra extension: .screen / .pm / .linearBurn',
    code: [
      '// from https://hydra.ojack.xyz/?code=JTBBYXdhaXQlMjBsb2FkU2NyaXB0KCUyMmh0dHBzJTNBJTJGJTJGY2RuLmpzZGVsaXZyLm5ldCUyRmdoJTJGZ2Vpa2hhJTJGaHlwZXItaHlkcmElNDBsYXRlc3QlMkZoeWRyYS1ibGVuZC5qcyUyMiklMEElMEFvc2MoMzApJTBBJTA5LnNjcmVlbihub2lzZSgzJTJDMSkucG0oKSklMEElMDkubGluZWFyQnVybihncmFkaWVudCgxKS5odWUoLjMpKSUwQSUwOS5vdXQoKSUwQQ%3D%3D',
      '',
      'await loadScript("https://cdn.jsdelivr.net/gh/geikha/hyper-hydra@latest/hydra-blend.js")',
      '',
      'osc(30)',
      '\t.screen(noise(3,1).pm())',
      '\t.linearBurn(gradient(1).hue(.3))',
      '\t.out()',
    ].join('\n'),
  },
  {
    title: 'shader park torus',
    description: 'shader-park-core extension — rotateX/Z + animated torus via sculptToHydraRenderer',
    code: [
      '// from https://hydra.ojack.xyz/?code=Y29uc3QlMjAlN0IlMjBzY3VscHRUb0h5ZHJhUmVuZGVyZXIlMjAlN0QlMjAlM0QlMjBhd2FpdCUyMGltcG9ydCglMjJodHRwcyUzQSUyRiUyRnVucGdrLmNvbSUyRnNoYWRlci1wYXJrLWNvcmUlMkZkaXN0JTJGc2hhZGVyLXBhcmstY29yZS5lc20uanMlMjIpJTBBJTBBc2N1bHB0VG9IeWRyYVJlbmRlcmVyKCgpJTIwJTNEJTNFJTIwJTdCJTBBJTA5JTA5cm90YXRlWCh0aW1lJTIwJTJGJTIwNSklMEElMDklMDlyb3RhdGVaKHRpbWUlMjAlMkYlMjAzKSUwQSUwOSUwOWRpc3BsYWNlKHNpbih0aW1lKSUyQyUyMDElMkMlMjAwKSUwQSUwOSUwOW1pcnJvck4oMyUyQyUyMDMpJTBBJTA5JTA5dG9ydXMoMC44JTJDJTIwMC4zOCUyMCUyQiUyMDAuMSUyMColMjBzaW4odGltZSkpJTBBJTA5JTdEKSUwQSUwOS5vdXQobzApJTBBJTBBcmVuZGVyKG8wKSUwQQ%3D%3D',
      '',
      'const { sculptToHydraRenderer } = await import("https://unpkg.com/shader-park-core/dist/shader-park-core.esm.js")',
      '',
      'sculptToHydraRenderer(() => {',
      '\trotateX(time / 5)',
      '\trotateZ(time / 3)',
      '\tdisplace(sin(time), 1, 0)',
      '\tmirrorN(3, 3)',
      '\ttorus(0.8, 0.38 + 0.1 * sin(time))',
      '})',
      '\t.out(o0)',
      '',
      'render(o0)',
    ].join('\n'),
  },
  {
    title: 'midi solid (note)',
    description: 'hydra-midi extension — note() drives red channel of solid() (needs MIDI device)',
    code: [
      '// from https://hydra.ojack.xyz/?code=JTJGJTJGJTIwWW91JTIwY2FuJTIwZWl0aGVyJTIwdXNlJTIwJTYwJTQwbGF0ZXN0JTYwJTIwb3IlMjBsb2FkJTIwYSUyMHNwZWNpZmljJTIwdmVyc2lvbiUyMHdpdGglMkMlMjBmb3IlMjBleGFtcGxlJTJDJTIwJTYwJTQwMC40LjAlNjAuJTBBYXdhaXQlMjBsb2FkU2NyaXB0KCUwQSUyMCUyMCdodHRwcyUzQSUyRiUyRmNkbi5qc2RlbGl2ci5uZXQlMkZucG0lMkZoeWRyYS1taWRpJTQwbGF0ZXN0JTJGZGlzdCUyRmluZGV4LmpzJyUwQSklMEElMEElMkYlMkYlMjBVc2UlMjBtaWRpJTIwbWVzc2FnZXMlMjBmcm9tJTIwYWxsJTIwY2hhbm5lbHMlMjBvZiUyMGFsbCUyMGlucHV0cy4lMEFhd2FpdCUyMG1pZGkuc3RhcnQoJTdCJTIwY2hhbm5lbCUzQSUyMCcqJyUyQyUyMGlucHV0JTNBJTIwJyonJTIwJTdEKSUwQSUyRiUyRiUyMFNob3clMjBhJTIwc21hbGwlMjBtaWRpJTIwbW9uaXRvciUyMChzaW1pbGFyJTIwdG8lMjBoeWRhJTI3cyUyMCU2MGEuc2hvdyglMjklNjApLiUwQW1pZGkuc2hvdygpJTBBJTBBJTJGJTJGJTIwVXNlJTIwYW55JTIwbm90ZSUyMHRvJTIwY29udHJvbCUyMHRoZSUyMHJlZCUyMGFtb3VudCUyMG9mJTIwaHlkcmEncyUyMCU2MHNvbGlkKCklNjAlMjBmdW5jdGlvbi4lMEFzb2xpZChub3RlKCcqJyklMkMlMjAwJTJDJTIwMSkub3V0KCklMEElMEElMkYlMkYlMjBPciUyQyUyMGlmJTIweW91JTIwYXJlJTIwdXNpbmclMjBhJTIvbWlkJTIwY29udHJvbGxlciUyMGFuZCUyMG5vdCUyMGFuJTIwa2V5Ym9hcmQlM0ElMEElMkYlMkYlMjBVc2UlMjBhJTIwY29udHJvbCUyMGNoYW5nZSUyMHZhbHVlJTIwdG8lMjBjb250cm9sJTIwdGhlJTIgcmVkJTIwYW1vdW50LiUwQSUyRiUyRiUyMHNvbGlkKGNjKDc0KSUyQyUyMDAlMkMlMjAxKS5vdXQoKQ%3D%3D',
      '',
      '// You can either use `@latest` or load a specific version with, for example, `@0.4.0`.',
      "await loadScript(",
      "  'https://cdn.jsdelivr.net/npm/hydra-midi@latest/dist/index.js'",
      ')',
      '',
      '// Use midi messages from all channels of all inputs.',
      "await midi.start({ channel: '*', input: '*' })",
      "// Show a small midi monitor (similar to hydra's `a.show()`).",
      'midi.show()',
      '',
      "// Use any note to control the red amount of hydra's `solid()` function.",
      "solid(note('*'), 0, 1).out()",
      '',
      '// Or, if you are using a midi controller and not a keyboard:',
      '// Use a control change value to control the red amount.',
      '// solid(cc(74), 0, 1).out()',
    ].join('\n'),
  },
]
